# Generated by Django 2.2.5 on 2019-11-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20191124_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='caprion',
            new_name='caption',
        ),
    ]
