# Generated by Django 2.2.5 on 2019-11-30 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20191126_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Conversation',
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='massage', to='conversations.Conversation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massage', to=settings.AUTH_USER_MODEL),
        ),
    ]
